01 Chapter Presentation Update
r4ds/bookclub-shinyui pull request #19
Opened 2024-11-09 00:41 UTC by AngelFelizR

2024-11-09 17:10 UTC, lgibson7 requested changes

2024-11-09 17:10 UTC, lgibson7 commented on index.Rmd
> +- Each week, a volunteer will present a chapter from the book after assigning it to themselves in the [Volunteers Spreadsheet](https://docs.google.com/spreadsheets/d/1HhA4HMB5LgpyPaF2KZbwwcdtB5RWfZrB
The shared notes are meant to be used by multiple book club cohorts, so it's best not to include links for a specific cohort unless explicitly stated. Please indicate that is the volunteer spreadsheet for bookclub-shinyui cohort 2.

2024-11-09 17:10 UTC, lgibson7 commented on index.Rmd
> +- Presentations will be recorded, and will be available on the [Data Science Learning Community YouTube Channel](https://www.youtube.com/playlist?list=PL3x6DOfs2NGhoKz3RSvwGxJYoCvE4MbnM).
The shared notes are meant to be used by multiple book club cohorts, so it's best not to include links for a specific cohort unless explicitly stated. Please link to the DSLC YouTube channel as <https://dslc.io/youtube>, and you can separately include a link to the playlist for bookclub-shinyui cohort 2 if you'd like. 

Note: The meeting recordings and chat log for each chapter are appended to the notes, so adding the playlist may be unnecessary. (Ex. bookclub-shinyui chapter 1 [meeting recording](https://r4ds.github.io/bookclub-shinyui/meeting-videos.html))

2024-11-10 03:26 UTC, AngelFelizR commented on index.Rmd
> +- Each week, a volunteer will present a chapter from the book after assigning it to themselves in the [Volunteers Spreadsheet](https://docs.google.com/spreadsheets/d/1HhA4HMB5LgpyPaF2KZbwwcdtB5RWfZrB
I understand, it's better to remove the link.

2024-11-10 03:26 UTC, AngelFelizR commented on index.Rmd
> +- Presentations will be recorded, and will be available on the [Data Science Learning Community YouTube Channel](https://www.youtube.com/playlist?list=PL3x6DOfs2NGhoKz3RSvwGxJYoCvE4MbnM).
No problem

2024-11-11 20:44 UTC, lgibson7 approved these changes
Looks good. Thanks Angel!

2024-11-12 01:04 UTC, merged